name: ci
on:
  push:
    branches:
      - main
      - master
      - development
  pull_request:
    branches:
      - main
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

    container:
      image: python:3.7-alpine3.9

    steps:

      - name: Install git, git-fast-import, gcc
        run: apk add git git-fast-import build-base

      - name: Checkout
        uses: actions/checkout@v2

      #- name: Set up Python 3.7
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: '3.7'


      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Deploy
        run: |
          git pull
          mkdocs gh-deploy --clean
